version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/spb_realty
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --host 0.0.0.0 --reload
  
  celery_worker:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/spb_realty
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    command: celery -A tasks.parse_sources worker --loglevel=info
  
  celery_beat:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/spb_realty
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    command: celery -A tasks.parse_sources beat --loglevel=info
  
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: spb_realty
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
