version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/spb_realty
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/spb_realty
      - ASYNC_DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/spb_realty
      - REDIS_URL=redis://redis:6379
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - CIAN_API_KEY=${CIAN_API_KEY}
      - YANDEX_API_KEY=${YANDEX_API_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --host 0.0.0.0 --reload
  
  celery_worker:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/spb_realty
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/spb_realty
      - ASYNC_DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/spb_realty
      - REDIS_URL=redis://redis:6379
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - CIAN_API_KEY=${CIAN_API_KEY}
      - YANDEX_API_KEY=${YANDEX_API_KEY}
    depends_on:
      - db
      - redis
    command: python -m celery -A tasks.parse_sources worker --loglevel=info
  
  celery_beat:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/spb_realty
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/spb_realty
      - ASYNC_DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/spb_realty
      - REDIS_URL=redis://redis:6379
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - CIAN_API_KEY=${CIAN_API_KEY}
      - YANDEX_API_KEY=${YANDEX_API_KEY}
    depends_on:
      - db
      - redis
    command: python -m celery -A tasks.parse_sources beat --loglevel=info

  frontend:
    build:
      context: ./miniapp
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./miniapp:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api
    command: npm run dev
  
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: spb_realty
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
